# Generated by Django 2.2.6 on 2020-09-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='اسم بازی')),
                ('describtions', models.TextField(blank=True)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='زمان ایجاد')),
                ('group_name', models.CharField(max_length=40, verbose_name='اسم گروه')),
                ('active', models.CharField(choices=[('AW', 'AWAITING'), ('DG', 'DOING'), ('DN', 'DONE'), ('RJ', 'REJECT')], max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='اسم بازی')),
            ],
        ),
    ]
