# Generated by Django 2.2.6 on 2020-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد'),
        ),
    ]
