# Generated by Django 2.2.6 on 2020-09-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200913_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url_game',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='private_address',
            field=models.SlugField(null=True),
        ),
    ]
