# Generated by Django 2.2.6 on 2020-09-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200914_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='url_game',
            new_name='template',
        ),
    ]
