# Generated by Django 2.2.6 on 2020-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200914_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
